/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author haros
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        s_fname = new javax.swing.JTextField();
        s_address = new javax.swing.JTextField();
        s_tel = new javax.swing.JTextField();
        s_parent_name = new javax.swing.JTextField();
        s_dob = new com.toedter.calendar.JDateChooser();
        s_class_combo = new javax.swing.JComboBox<>();
        btn_s_add = new javax.swing.JButton();
        btn_s_update = new javax.swing.JButton();
        btn_s_delete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_s_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        s_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(56, 159, 214));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Address");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DOB");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telephone No");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Parent's Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Class");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 310, -1, -1));

        s_fname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(s_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 190, -1));

        s_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(s_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, -1));

        s_tel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(s_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 190, -1));

        s_parent_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(s_parent_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, -1));
        jPanel2.add(s_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 190, -1));

        s_class_combo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        s_class_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1A", "1B", "1C", "2A", "2B", "2C", "3A", "3B", "3C", "4A", "4B", "5A", "5B", "6A", "6B", "7A", "7B", "8A", "8B", "9A", "9B", "10", "11", "12A", "12B", "13A", "13B" }));
        jPanel2.add(s_class_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 190, -1));

        btn_s_add.setBackground(new java.awt.Color(0, 255, 0));
        btn_s_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_s_add.setText("ADD");
        jPanel2.add(btn_s_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 90, 30));

        btn_s_update.setBackground(new java.awt.Color(255, 255, 0));
        btn_s_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_s_update.setText("UPDATE");
        jPanel2.add(btn_s_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 90, 30));

        btn_s_delete.setBackground(new java.awt.Color(255, 0, 51));
        btn_s_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_s_delete.setText("DELETE");
        jPanel2.add(btn_s_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 90, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_s_back.setBackground(new java.awt.Color(153, 153, 153));
        btn_s_back.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_s_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_s_back.setText("Back");
        btn_s_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(btn_s_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 100, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 360, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 540));

        s_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Full Name", "Address", "DOB", "Telphone No", "Parent's Name", "Class"
            }
        ));
        jScrollPane1.setViewportView(s_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 610, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_s_add;
    private javax.swing.JButton btn_s_back;
    private javax.swing.JButton btn_s_delete;
    private javax.swing.JButton btn_s_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField s_address;
    private javax.swing.JComboBox<String> s_class_combo;
    private com.toedter.calendar.JDateChooser s_dob;
    private javax.swing.JTextField s_fname;
    private javax.swing.JTextField s_parent_name;
    private javax.swing.JTable s_table;
    private javax.swing.JTextField s_tel;
    // End of variables declaration//GEN-END:variables
}
