/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author haros
 */
public class teacher extends javax.swing.JFrame {

    /**
     * Creates new form teacher
     */
    public teacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_fname_txt = new javax.swing.JTextField();
        t_address_txt = new javax.swing.JTextField();
        t_dob = new com.toedter.calendar.JDateChooser();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        t_subject_combo = new javax.swing.JComboBox<>();
        t_section_combo = new javax.swing.JComboBox<>();
        btn_t_add = new javax.swing.JButton();
        btn_t_update = new javax.swing.JButton();
        btn_t_delete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_t_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(56, 159, 214));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Full Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Address");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("DOB");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Telephone No");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Subject");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Section");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 360, -1, -1));

        t_fname_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(t_fname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        t_address_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(t_address_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, -1));
        jPanel2.add(t_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 180, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 180, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 180, -1));

        t_subject_combo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t_subject_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mathematics", "Science", "Sinhala", "English", "Music", "ICT", "History" }));
        jPanel2.add(t_subject_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 180, -1));

        t_section_combo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t_section_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primary", "Junior", "Senior" }));
        jPanel2.add(t_section_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 180, -1));

        btn_t_add.setBackground(new java.awt.Color(51, 255, 0));
        btn_t_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_t_add.setText("ADD");
        btn_t_add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btn_t_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 90, 30));

        btn_t_update.setBackground(new java.awt.Color(255, 255, 0));
        btn_t_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_t_update.setText("UPDATE");
        btn_t_update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btn_t_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 90, 30));

        btn_t_delete.setBackground(new java.awt.Color(255, 0, 51));
        btn_t_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_t_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_t_delete.setText("DELETE");
        btn_t_delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btn_t_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 90, 30));

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_t_back.setBackground(new java.awt.Color(153, 153, 153));
        btn_t_back.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_t_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_t_back.setText("Back");
        btn_t_back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(btn_t_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 360, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 540));

        t_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Full Name", "Address", "DOB", "Email", "Telephone", "Subject", "Section"
            }
        ));
        jScrollPane1.setViewportView(t_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 6, 620, 522));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_t_add;
    private javax.swing.JButton btn_t_back;
    private javax.swing.JButton btn_t_delete;
    private javax.swing.JButton btn_t_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField t_address_txt;
    private com.toedter.calendar.JDateChooser t_dob;
    private javax.swing.JTextField t_fname_txt;
    private javax.swing.JComboBox<String> t_section_combo;
    private javax.swing.JComboBox<String> t_subject_combo;
    private javax.swing.JTable t_table;
    // End of variables declaration//GEN-END:variables
}
